"use client";
import { useEffect, useState } from "react";
import OwnerGuard from "../../components/OwnerGuard";
import { supabase } from "../../lib/supabase";
import { TURFS } from "../../lib/constants";
import { formatHour, getTodayDate } from "../../lib/utils";
export default function AdminPage(){ return <OwnerGuard><Dashboard/></OwnerGuard> }
function Dashboard(){
 const [bookings,setBookings]=useState([]), [rules,setRules]=useState([]), [msg,setMsg]=useState(null);
 const [form,setForm]=useState({turf_id:TURFS[0].id,day_type:"all",start_hour:0,end_hour:24,price_per_hour:""});
 async function loadAll(){ const [{data:bookingRows},{data:ruleRows}] = await Promise.all([supabase.from("bookings").select("*").order("booking_date",{ascending:false}).limit(200),supabase.from("pricing_rules").select("*").order("created_at",{ascending:false})]); setBookings(bookingRows||[]); setRules(ruleRows||[]); }
 useEffect(()=>{loadAll(); const ch=supabase.channel("admin-live").on("postgres_changes",{event:"*",schema:"public",table:"bookings"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"pricing_rules"},loadAll).subscribe(); return ()=>supabase.removeChannel(ch);},[]);
 const today=getTodayDate(); const todayBookings=bookings.filter(b=>b.booking_date===today&&b.booking_status==="confirmed"); const totalHours=todayBookings.reduce((s,b)=>s+Number(b.duration_hours),0); const totalRevenue=todayBookings.reduce((s,b)=>s+Number(b.booking_price),0);
 async function addRule(){ setMsg(null); if(!form.price_per_hour||Number(form.end_hour)<=Number(form.start_hour)){setMsg({type:"error",text:"Enter valid pricing rule values."}); return;} const {error}=await supabase.from("pricing_rules").insert({turf_id:form.turf_id,day_type:form.day_type,start_hour:Number(form.start_hour),end_hour:Number(form.end_hour),price_per_hour:Number(form.price_per_hour),is_active:true}); if(error){setMsg({type:"error",text:error.message}); return;} setMsg({type:"success",text:"Pricing rule added."}); setForm({...form,price_per_hour:""}); loadAll();}
 async function cancelBooking(id){ const {error}=await supabase.from("bookings").update({booking_status:"cancelled"}).eq("id",id); if(error){alert(error.message); return;} await supabase.from("booking_slots").delete().eq("booking_id",id); loadAll(); }
 async function deleteRule(id){ await supabase.from("pricing_rules").delete().eq("id",id); loadAll(); }
 return <div className="container"><div className="hero"><div><h1>📊 Admin Dashboard</h1><p>Live dashboard for both owners</p></div><div className="actions"><a className="btn secondary" href="/">Booking Page</a><button className="btn danger" onClick={async()=>{await supabase.auth.signOut(); location.href="/login";}}>Logout</button></div></div>
 <div className="card"><h2>Today summary</h2><div className="stats"><div className="stat"><span>Total bookings today</span><strong>{todayBookings.length}</strong></div><div className="stat"><span>Total hours booked today</span><strong>{totalHours}</strong></div><div className="stat"><span>Revenue today</span><strong>₹{totalRevenue}</strong></div></div>
 <h3>Hours by turf</h3><table><thead><tr><th>Turf</th><th>Hours today</th></tr></thead><tbody>{TURFS.map(t=>{const hrs=todayBookings.filter(b=>b.turf_id===t.id).reduce((s,b)=>s+Number(b.duration_hours),0); return <tr key={t.id}><td>{t.name}</td><td>{hrs}</td></tr>})}</tbody></table></div>
 <div className="card"><h2>Add Pricing Rule</h2><div className="grid three"><div><label>Turf</label><select value={form.turf_id} onChange={e=>setForm({...form,turf_id:e.target.value})}>{TURFS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div><label>Day type</label><select value={form.day_type} onChange={e=>setForm({...form,day_type:e.target.value})}><option value="all">All</option><option value="weekday">Weekday</option><option value="weekend">Weekend</option></select></div><div><label>Price / hour</label><input type="number" value={form.price_per_hour} onChange={e=>setForm({...form,price_per_hour:e.target.value})}/></div><div><label>Start hour</label><select value={form.start_hour} onChange={e=>setForm({...form,start_hour:Number(e.target.value)})}>{Array.from({length:24},(_,i)=><option key={i} value={i}>{formatHour(i)}</option>)}</select></div><div><label>End hour</label><select value={form.end_hour} onChange={e=>setForm({...form,end_hour:Number(e.target.value)})}>{Array.from({length:24},(_,i)=>i+1).map(i=><option key={i} value={i}>{formatHour(i)}</option>)}</select></div></div><div className="actions"><button className="btn" onClick={addRule}>Add Pricing Rule</button></div>{msg&&<div className={msg.type}>{msg.text}</div>}</div>
 <div className="card"><h2>Pricing Rules</h2><table><thead><tr><th>Turf</th><th>Day type</th><th>Time</th><th>Price/hour</th><th>Action</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td>{TURFS.find(t=>t.id===r.turf_id)?.name||r.turf_id}</td><td>{r.day_type}</td><td>{formatHour(r.start_hour)} - {formatHour(r.end_hour)}</td><td>₹{r.price_per_hour}</td><td><button className="btn danger" onClick={()=>deleteRule(r.id)}>Delete</button></td></tr>)}</tbody></table></div>
 <div className="card"><h2>Bookings</h2><table><thead><tr><th>Date</th><th>Turf</th><th>Slot</th><th>Hours</th><th>Price</th><th>Customer</th><th>Phone</th><th>Email</th><th>Booked by</th><th>Status</th><th>Action</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td>{b.booking_date}</td><td>{b.turf_name}</td><td>{formatHour(b.start_hour)} - {formatHour(b.end_hour)}</td><td>{b.duration_hours}</td><td>₹{b.booking_price}</td><td>{b.customer_name}</td><td>{b.customer_phone}</td><td>{b.customer_email||""}</td><td>{b.booked_by_email}</td><td>{b.booking_status}</td><td>{b.booking_status==="confirmed"?<button className="btn danger" onClick={()=>cancelBooking(b.id)}>Cancel</button>:""}</td></tr>)}</tbody></table></div></div>
}
